# Generated by Django 2.1.2 on 2018-12-15 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_uer_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uer_info',
            name='user',
        ),
        migrations.DeleteModel(
            name='Uer_Info',
        ),
    ]
