# Generated by Django 2.1.2 on 2018-12-15 12:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20181215_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2018, 12, 15, 12, 9, 11, 442779, tzinfo=utc)),
        ),
    ]
